name: Deploy to Google App Engine
on:
    push:
        branches:
            - main
jobs:
    build:
        name: GAE Deploy
        runs-on: ubuntu-latest
        steps:
            # - uses: actions/checkout@v2
            - uses: google-github-actions/deploy-appengine@v0
              with:
                  credentials: ${{ secrets.gcp_credentials }}
