name: Deploy to Google App Engine
on:
    push:
        branches:
            - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm test -- --watchAll=false
    - run: npm run build
    
    - uses: actions/upload-artifact@v3
      with:
        path: |
          dist/
          package.json
          app.yaml
        

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -a
      - run: unzip artifact
      - run: ls -a
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - uses: 'google-github-actions/deploy-appengine@v0'

